### PR TITLE
Created an SQL script for Orders count and amount of user.

### PR DESCRIPTION
**Pull request by jagadeesh42**
This SQL Query helps in getting the number of orders a customers has placed and the total amount he paid for all the orders.

### CODE REVIEW

**Comment by jagadeesh42** [comment]
@lxmn-22 Could you please review the code and merge my pull request.

**Review by lxmn-22 — APPROVED** [review]

**Comment by lxmn-22** [comment]
Merged buddy. 👍

**Comment by jagadeesh42** [comment]
Thank you for merging @lxmn-22. Could you please also add the hacktoberfest2024 label. So that it can helps me to partcipate in that event, Laxman.

**Comment by lxmn-22** [comment]
@jagadeesh42 already there mate.

**Comment by lxmn-22** [comment]
Done. 👍🏼

**Pull request merged**
